services:
  koi-client:
    container_name: koi_client
    image: ${DOCKER_USERNAME}/koiclient:latest
    restart: always
    ports:
      -3000:80
    networks:
      - koiveterinary_network

networks:
  koiveterinary_network:
    name: koiveterinary_network
    external: true